services:
  keycloak:
    container_name: keycloak_demo
    image: quay.io/keycloak/keycloak:25.0.5   # ✔ New API, no /auth prefix
    ports:
      - 9090:8080                             # ✔ Host=9090, Container=8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    volumes:
      - keycloak_data:/opt/keycloak/data
    command:
      - 'start-dev'                            # ✔ Dev mode
volumes:
  keycloak_data:
